backend:
  name: github
  repo: rassacnivek/starter-gatsby2

media_folder: static/assets
public_folder: /assets

collections:
  - name: product
    label: Produit
    folder: products
    create: true
    fields:
      - { name: title, required: true, label: Titre }
      - { name: price, required: true, label: Prix }
      - { name: description, required: true, label: Description, widget: markdown }
      - { name: image, required: true, label: Image, widget: image }
      - { name: sku, required: false, label: Sku }
      - { name: path, required: false, label: Path }
  - name: blog
    label: Blog
    folder: articles
    create: true
    fields: 
      - { name: title, required: true, label: Titre}
      - { name: description, required: true, label: Description, widget: markdown}
      - { name: image, required: true, label: Image, widget: image}
      - { name: path, required: false, label: Path}
  - name: page
    label: Pages
    folder: pages
    create: true
    fields: 
      - { name: title, required: true, label: Titre}
      - { name: description, required: true, label: Description, widget: markdown}
      - { name: image, required: true, label: Image, widget: image}
      - { name: path, required: false, label: Path}
      - { name: type, required: true, label: Type, widget: "list", allow_add: false, default: ["about page", "custom page"]}